<a href="https://colab.research.google.com/github/krishgit042023/Bank-Churn-Rate/blob/main/ANN_Bank_Churn_Rate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**importing libraries**

In [ ]:
# prompt: import numpy pandas and tensor flow

import numpy as np
import pandas as pd
import tensorflow as tf


# **Part 1 :- Data Preprocessing**

**importing training dataset**

In [ ]:
# prompt: check the version of tensor flow

tf.__version__


'2.17.1'

In [ ]:
# prompt: import train dataset

train_df = pd.read_csv('/content/Churn_Modelling.csv')

train_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
# prompt: create features and target

# Create features (X) and target (y)
X = train_df.iloc[:, 3:-1].values # Features from column 3 to second last
y = train_df.iloc[:, -1].values   # Target variable (last column)

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


**Encoding categorical data**

In [ ]:
# prompt: encode the categorical column

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)


from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
X

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
# prompt: split the dataset into train and test set

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
# prompt: apply feature scaling

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# **Part 2:- Building the ANN**

**initializing the ANN**

In [ ]:
# prompt: initialize the ANN

ann = tf.keras.models.Sequential()


**adding the input layer and the first hidden layer**

In [ ]:
# prompt: add the input layer and the first hidden layer

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**adding the second hidden layer**

In [ ]:
# prompt: add the second hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


**adding the output layer**

In [ ]:
# prompt: add the output layer

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# **Part 3:- Training the ANN**

**compiling the ANN**

In [ ]:
# prompt: compile the ANN

ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


**training the ANN on the Training set**

In [ ]:
# prompt: train the ANN on the Training set

ann.fit(X_train, y_train, batch_size = 32, epochs = 100)


Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.7957 - loss: 0.5238
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7929 - loss: 0.4639
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7929 - loss: 0.4450
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8054 - loss: 0.4300
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8181 - loss: 0.4135
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8145 - loss: 0.4222
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8301 - loss: 0.3983
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8331 - loss: 0.4037
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8329 - loss: 0.4024
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8354 - loss: 0.3919
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8385 - loss: 0.3934
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

# **Part 4:- Making the predictions and evaluating the model**

**predicting the result on a single observation**

In [ ]:
# prompt: predict the result on a single observation

print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)  #sigmoid function gives probability


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step
[[False]]


In [ ]:
# prompt: check the accuracy

# Predicting the Test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
[[1496   99]
 [ 182  223]]


0.8595

In [ ]:
# prompt: show the final adjusted weights

print(ann.get_weights())

[array([[ 1.17080852e-01, -1.69164672e-01, -1.08542815e-02,
         3.08219671e-01,  1.63312852e-01, -4.46457684e-01],
       [ 2.91439235e-01, -4.05677438e-01, -3.55744630e-01,
         4.83773202e-01, -1.63361043e-01, -2.87880123e-01],
       [ 1.05270751e-01, -2.81135198e-02, -1.66061282e-01,
         2.79115051e-01,  2.07932979e-01, -3.22492629e-01],
       [ 6.67432963e-04,  9.30068269e-02, -8.85815993e-02,
        -9.96506885e-02, -2.78911814e-02,  2.97489557e-02],
       [ 3.63107800e-01,  6.17921174e-01,  6.61225319e-02,
         2.12982014e-01,  7.34413862e-02, -2.89850503e-01],
       [ 5.01416437e-02,  1.32937312e-01, -2.96751082e-01,
         1.23192990e+00,  1.14837721e-01, -6.93350315e-01],
       [-3.69895622e-02,  9.55382660e-02, -3.17462012e-02,
        -3.92706133e-02, -3.08812633e-02, -8.41646865e-02],
       [-4.32525426e-01, -1.91073969e-01,  4.47059162e-02,
        -4.57807362e-01,  3.09780568e-01,  1.81131233e-02],
       [-5.81591606e-01,  2.37645641e-01,  6.08